[package]
name = "linkerd2-lock"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false
description = """
A middleware that provides mutual exclusion.
"""

[dependencies]
futures = "0.1"
tokio = "0.1"
tower = "0.1"
